config/routes.rb
Zilibang::Application.routes.draw do

  get "notices/index", :as => "accept_account"
  get "notices/error", :as => "refuse_account"
  get "notices/error_404", :as=> "error_404"
  get "notices/error_power", :as=> "error_power"
  get "home/index"

  root :to => "home#index"
  resource :user_session
  match "login" => "user_sessions#new", :as => :login
  match "register_check_instructions/:id" => "users#register_check_instructions", :as => :register_check_instructions
  match 'logout' => "user_sessions#destroy", :as => :logout
  get 'buyer_sure/:id' => "comments#buyer_sure", :as => :buyer_sure
  get 'buyer_cancel/:id' => "comments#buyer_cancel",  :as => :buyer_cancel
  get 'employer_sure/:id' => "comments#employer_sure", :as => :employer_sure
  get 'employer_cancel/:id' => "comments#employer_cancel",  :as => :employer_cancel
  get 'overpost/:id' => "posts#over", :as => :over_post
  get 'finish/:id' => "posts#finish", :as => :finish_post
  get 'pay_sure/:id' => "home#pay_sure", :as => :pay_sure_post
  get 'pay/:id' => "home#pay", :as => :pay_post
  post 'report_employer' => "comments#report_employer", :as => :report_employer
  post 'report_buyer' => "comments#report_buyer", :as => :report_buyer
  post 'verify' => "comments#verify_code", :as => :verify_code
  get 'mailer' => "home#mailer", :as => :mailer

  get 'forgot_password' => "users#forgot_password", :as => :forgot_password
  post 'forgot_password_sender' => "users#forgot_password_sender", :as => :forgot_password_sender
  get 'forgot_check_instructions/:id' => "users#forgot_check_instructions", :as => :forgot_check_instructions
  put 'update_user' => "users#update", :as => :update_user
  
  
  resources :users, :only => [:new, :create]
  resources :profiles, :only => [:show]
  get 'worker_show/:id' => "profiles#worker_show", :as => :worker_show
  get 'bussiness_show/:id' => "profiles#bussiness_show", :as => :bussiness_show
  resources :posts do
    post 'add_comment'
  end

  namespace :admin do
    get 'main/index'
    root :to => "main#index"
    resources :posts, :except => [:destroy]
    post 'posts/:id/pay' => "posts#pay", :as => :pay_post
    post 'posts/:id/destroy' => "posts#destroy", :as => :destroy_post
    resources :comments, :only => [:index, :edit, :update]
    post 'comments/:id/destroy' => "comments#destroy", :as => :destroy_comment
    resources :users do
      collection do
        get "change_password"
        put "update_password"
      end
    end
    post 'tags/:id/destroy' => "tags#destroy", :as => :destroy_tag
    resources :tags, :only => [:index, :new, :create]
    
  end

  namespace :center do
    root :to => "main#index"
    #resources :profiles, :only => [:show, :edit, :update]
    get 'profile' => 'profiles#show', :as => :profile
    get 'profile/edit' => 'profiles#edit', :as => :edit_profile
    put 'profile' => 'profiles#update', :as => :update_profile

    get 'change_password' => 'profiles#change_password', :as => :change_password
    put 'update_password' => 'profiles#password_update', :as => :update_change_password
    get 'messages' => 'messages#index', :as => :messages
    get 'message/show/:name' => 'messages#show',  :as => :show_message
    get 'messages/new' => 'messages#new', :as => :new_message
    post 'messages' => 'messages#create'
    post 'messages/:id/destroy' =>  'messages#destroy',  :as => :destroy_message
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  apply_simple_captcha
  validates_numericality_of :price, :only_integer => true,
    :greater_than_or_equal_to => 10
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < Admin::BaseController
  #  load_and_authorize_resource
  main_nav_highlight :content
  sec_nav_highlight :comments
  def index
    @comments = Comment.order("created_at DESC").paginate(:page => params[:page]||1, :per_page => 30)
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    @comment.update_attributes(params[:comment])
    flash[:notice] = "update successful"
    redirect_to admin_comments_path()
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    flash[:notice] = "destroy successful"
    redirect_to admin_comments_path()
  end


end

app/controllers/comments_controller.rb
# coding: utf-8
class CommentsController < ApplicationController
  def buyer_sure
    comment = Comment.find(params[:id])
    if comment.post.user == current_user
      comment.buyer_sure = true
      comment.save
      Message.create(:sender => User.find(1),:receiver => comment.user,:content =>"企业确定，请确认:#{comment.post.title}#{post_path(comment)}")
      current_user.delay.deliver_buyer_sure(comment.user,comment.post)
      redirect_to post_path(comment.post)
    end
  end

  def buyer_cancel
    comment = Comment.find(params[:id])
    if comment.post.user == current_user
      comment.buyer_sure = false
      comment.employer_sure = false
      comment.save
      Message.create(:sender => User.find(1),:receiver => comment.user,:content =>"企业取消任务")
      current_user.delay.deliver_buyer_cancel(comment.user,comment.post)
      redirect_to post_path(comment.post)
    end
  end

  def employer_sure
    comment = Comment.find(params[:id])
    if comment.user == current_user
      comment.employer_sure = true
      comment.save
      Message.create(:sender => User.find(1),:receiver => comment.post.user,:content =>"用户已确定")
#      current_user.delay.deliver_employer_sure(comment.post.user,comment.post)
      redirect_to post_path(comment.post)
    end
  end

  def employer_cancel
    comment = Comment.find(params[:id])
    if comment.user == current_user
      comment.employer_sure = false
      comment.save
      Message.create(:sender => User.find(1),:receiver => comment.post.user,:content =>"用户已取消")
      current_user.delay.deliver_employer_cancel(comment.post.user,comment.post)
      redirect_to post_path(comment.post)
    end
  end

  def verify_code

    code = params[:code]
    comment = Comment.find(params[:id])
    if current_user == comment.user
      if comment.code == nil or comment.code != code
        flash[:notice] = "输入错误1"
        redirect_to post_path(comment.post)
      elsif comment.code == code and simple_captcha_valid?
        comment.verified = true
        user = comment.user
        comment.post.skill_list.each do |tag|
          puts "#{tag}--\n"
          user.add_score!(1, tag)
        end
        comment.save
        Message.create(:sender => User.find(1), :receiver => comment.user, :content => "验证成功")
        current_user.delay.deliver_verify_code(comment.user,comment.post)
        flash[:notice] = "ok!"
        redirect_to post_path(comment.post)
      else
        flash[:notice] = "输入错误2"
        redirect_to post_path(comment.post)
      end
    else
      flash[:notice] = "who's ur daddy?"
      redirect_to post_path(comment.post)
    end
  end

  def report_buyer
    level = case
    when params[:level] == "好评"
      2
    when params[:level] == "中评"
      1
    when params[:level] == "差评"
      -1
    end
    comment = Comment.find(params[:id])
    comment.buyer_content = params[:content]
    comment.buyer_level = level
    comment.save
    Message.create(:sender => User.find(1),:receiver => comment.post.user,:content =>"用户已评价")
#    current_user.delay.deliver_report_buyer(comment.post.user,comment.post)
    user = comment.user
    #    comment.post.skill_list.each do |tag|
    #      puts "#{tag}--\n"
    #      user.add_score!(level, tag)
    #    end
    user.goodwill += level
    user.save
    flash[:notice] = "report success"
    redirect_to post_path(comment.post)
  end

  def report_employer
    level = case
    when params[:level] == "好评"
      2
    when params[:level] == "中评"
      1
    when params[:level] == "差评"
      -1
    end
    comment = Comment.find(params[:id])
    comment.employer_content = params[:content]
    comment.employer_level = level
    comment.save
    Message.create(:sender => User.find(1),:receiver => comment.user,:content =>"企业已评价")
#    current_user.delay.deliver_report_employer(comment.user,comment.post)
    user = comment.post.user
    #    comment.post.skill_list.each do |tag|
    #      user.add_score!(level, tag)
    #    end
    user.goodwill += level
    user.save
    flash[:notice] = "report success"
    redirect_to post_path(comment.post)
  end




end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/admin/comments/_entries.html.erb
<%= will_paginate @comments %>
<table>
  <thead>
    <tr>
      <th>id</th>
      <th>content</th>
      <th>price</th>
      <th>code</th>
      <th>function</th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td>
          <%= comment.id %>
        </td>
        <td><%= comment.content%></td>
        <td><%= comment.price %></td>
        <td><%= comment.code %></td>
        <td>
          <%= link_to "edit", edit_admin_comment_path(comment), :title => :edit, :class => "edit" %>&nbsp;
          <form action="<%= admin_destroy_comment_path(comment) %>" method="post">
            <input class="destroy" id="comment_destroy" type="submit" value="删除"></input>
          </form>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @comments %>

app/views/admin/comments/_form.html.erb
<%= form.inputs do %>
  <%= form.input :price, :input_html => { :class => "text-input medium-input" } %>
  <%= form.input :content, :input_html => { :class => "text-input medium-input" } %>
  <%= form.input :code, :input_html => { :class => "text-input medium-input" } %>

<% end %>

<%= form.buttons do %>
  <%= form.commit_button :button_html => { :class => "button" } %>
<% end %>

app/views/admin/comments/edit.html.erb
<h3>任务管理</h3>

<ul class="shortcut-buttons-set">
	<li><%= link_to "返回控制面板", admin_root_path(), :class => "shortcut-button home" %></li>
	<li><%= link_to "返回任务列表", admin_comments_path(), :class => "shortcut-button episode" %></li>
</ul>

<div class="clear"></div>

<div class="content-box">
	<div class="content-box-header">
		<h3>修改任务</h3>
	</div>

	<div class="content-box-content">
		<%= semantic_form_for(@comment, :url => admin_comment_path(@comment)) do |f| %>
			<%= render :partial => 'form', :object => f %>
		<% end %>
	</div>
</div>

app/views/admin/comments/index.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>
<h2>留言展示</h2>

<ul class="shortcut-buttons-set">
	<li><%= link_to "返回控制面板", admin_root_path(), :class => "shortcut-button home" %></li>
</ul>

<div class="clear"></div>

<div class="content-box">
	<div class="content-box-header">
		<h3>留言列表</h3>
	</div>

	<div class="content-box-content">
		<% if @comments.blank? %>
			<p>暂无任务</p>
		<% else %>
			<%= render "entries" %>
		<% end %>
	</div>
</div>