config/routes.rb
Zilibang::Application.routes.draw do

  get "notices/index", :as => "accept_account"
  get "notices/error", :as => "refuse_account"
  get "notices/error_404", :as=> "error_404"
  get "notices/error_power", :as=> "error_power"
  get "home/index"

  root :to => "home#index"
  resource :user_session
  match "login" => "user_sessions#new", :as => :login
  match "register_check_instructions/:id" => "users#register_check_instructions", :as => :register_check_instructions
  match 'logout' => "user_sessions#destroy", :as => :logout
  get 'buyer_sure/:id' => "comments#buyer_sure", :as => :buyer_sure
  get 'buyer_cancel/:id' => "comments#buyer_cancel",  :as => :buyer_cancel
  get 'employer_sure/:id' => "comments#employer_sure", :as => :employer_sure
  get 'employer_cancel/:id' => "comments#employer_cancel",  :as => :employer_cancel
  get 'overpost/:id' => "posts#over", :as => :over_post
  get 'finish/:id' => "posts#finish", :as => :finish_post
  get 'pay_sure/:id' => "home#pay_sure", :as => :pay_sure_post
  get 'pay/:id' => "home#pay", :as => :pay_post
  post 'report_employer' => "comments#report_employer", :as => :report_employer
  post 'report_buyer' => "comments#report_buyer", :as => :report_buyer
  post 'verify' => "comments#verify_code", :as => :verify_code
  get 'mailer' => "home#mailer", :as => :mailer

  get 'forgot_password' => "users#forgot_password", :as => :forgot_password
  post 'forgot_password_sender' => "users#forgot_password_sender", :as => :forgot_password_sender
  get 'forgot_check_instructions/:id' => "users#forgot_check_instructions", :as => :forgot_check_instructions
  put 'update_user' => "users#update", :as => :update_user
  
  
  resources :users, :only => [:new, :create]
  resources :profiles, :only => [:show]
  get 'worker_show/:id' => "profiles#worker_show", :as => :worker_show
  get 'bussiness_show/:id' => "profiles#bussiness_show", :as => :bussiness_show
  resources :posts do
    post 'add_comment'
  end

  namespace :admin do
    get 'main/index'
    root :to => "main#index"
    resources :posts, :except => [:destroy]
    post 'posts/:id/pay' => "posts#pay", :as => :pay_post
    post 'posts/:id/destroy' => "posts#destroy", :as => :destroy_post
    resources :comments, :only => [:index, :edit, :update]
    post 'comments/:id/destroy' => "comments#destroy", :as => :destroy_comment
    resources :users do
      collection do
        get "change_password"
        put "update_password"
      end
    end
    post 'tags/:id/destroy' => "tags#destroy", :as => :destroy_tag
    resources :tags, :only => [:index, :new, :create]
    
  end

  namespace :center do
    root :to => "main#index"
    #resources :profiles, :only => [:show, :edit, :update]
    get 'profile' => 'profiles#show', :as => :profile
    get 'profile/edit' => 'profiles#edit', :as => :edit_profile
    put 'profile' => 'profiles#update', :as => :update_profile

    get 'change_password' => 'profiles#change_password', :as => :change_password
    put 'update_password' => 'profiles#password_update', :as => :update_change_password
    get 'messages' => 'messages#index', :as => :messages
    get 'message/show/:name' => 'messages#show',  :as => :show_message
    get 'messages/new' => 'messages#new', :as => :new_message
    post 'messages' => 'messages#create'
    post 'messages/:id/destroy' =>  'messages#destroy',  :as => :destroy_message
  end

end

app/controllers/home_controller.rb
# coding: utf-8
class HomeController < ApplicationController
  def index
    @posts = Post.limit(10).order("created_at DESC")
  end

  def pay_sure
    @post = Post.find(params[:id])
    @comments = []
    @price = 0
    @post.comments.each do |comment|
      if comment.employer_sure == true and comment.buyer_sure == true
        @comments << comment
        @price += comment.price
      end
    end
  end

  def pay
    @post = Post.find(params[:id])
    if current_user == @post.user
      @post.paid = true
      @post.state = "雇主已经预付押金，等待中标者输入提现密码。"
      @post.save
      @verify_codes = []
      @post.comments.each do |comment|
        comment.code = verification
        comment.save
        @verify_codes << comment.user.profile.name.to_s+':'+comment.code.to_s
        Message.create(:sender => User.find(1),:receiver => comment.user,:content => "企业已付款")
        current_user.delay.deliver_pay(comment.user,@post)
      end
      content = "<p>您发布的任务:#{@post.title} 已经付款，以下是各位工人的提款密码，请妥善保存，当确定工作完成后发放给工人，工人借此在自强帮网站上领取报酬</p>"
      @post.comments.each do |comment|
        if comment.code != nil
          content += "<p>#{comment.user.profile.name}:#{comment.code}</p>"
        end
      end
      Message.create(:sender => User.find(1),:receiver => @post.user,:content => content)
      current_user.delay.deliver_pay_code(@post.user,@post)
      flash[:notice] = "支付成功,请到您的用户中心查看您雇佣的工人的提现密码，并且我们已经把提现密码发送到您的邮箱中，请妥善保存！"
      redirect_to @post
    
    end
  end

  def mailer
    current_user.delay.deliver_register_instructions!
    flash[:notice] = "重新发送验证邮件成功，请再次进入邮箱查收。"
    redirect_to root_url
  end
end

app/helpers/home_helper.rb
# coding: utf-8

module HomeHelper
  def join_skills(post)
    post.skills.map { |t| t.name }.join (", ")
  end

  def how_long_over?(post)
    result = ""
    delta = post.created_at + post.longtime*24*60*60 - Time.now
    delta = delta.to_i
    if delta <= 0
      "结束了！"
    else
      if delta > 24*60*60
        buffer = delta/(24*60*60)
        result += "#{buffer}天"
        delta -= buffer*24*60*60
      end

      if delta > 60*60
        buffer = delta/(60*60)
        result += "#{buffer}小时"
        delta -= buffer*60*60
      end

      if delta > 60
        buffer = delta/60
        result += "#{buffer}分"
        delta -= buffer*60
      end

      result += "#{delta}秒"

      result
    end
  end
end

app/views/home/index.html.erb
<% content_for :banner do %>
<div id="ziqiangbang-banner">
        <div class="ziqiangbang-space left" style="width:200px; min-height:77px;"></div>
        <div class="total-preview left" align="left">
          <div style="padding:13px;" class="left">
            <b style="font-weight:bold;font-size:16px;color: #666">累计所有:</b>
            |
            <b style="color:#666"> ngo:0元</b>
            |
            <b style="color:#666"> 任务总数:
              <%= Post.all.count %>
              个</b>
            |
            <b style="color:#666"> 人才数:
              <%= User.all.count %>
              个</b>

          </div>
          <div class="ziqiangbang-logo2 right">

          </div>

        </div>
        <div class="ziqiangbang-space" style="width:800px; min-height:34px;"></div>
        <div class="c"></div>
        <div class="ziqiangbang-space left"></div>
        <div id="intro">

          <div style="text-shadow: 1px 1px 1px #666;font-size: 36px;font-weight: bold;font-family:黑体;" align="left">
			自强帮的初衷
          </div>

          <div style="padding:6px;font-size: 15px;font-weight: bold;font-family:黑体;" align="left">
            <p>自强帮由一个简单的想法，一个积极向上的生活，一个努力帮助他人的心态，</p>
            <p>一个只属于完善人格的每一位伙伴所存在的一个平台。</p>
          </div>

          <div align="left" style="padding:6px; font-size: 12px; width:400px" class="left">
            <ul class="welcome-list">
              <li>一个简单的想法，大学生是不是应该独立了？</li>
              <li>是不是应该不向家里伸手要生活费了？</li>
              <li>是不是应该抛弃恶习不断完善自己？</li>
              <li>那么我想告诉大家，自强帮就是“自立自强，帮助他人”</li>
              <li>一些需要帮助的人可能此时整需要我们的一臂之力。</li>
            </ul>
          </div>

        </div>

        <div id="enter" class="left">
          <div class="post-button">
            <%= link_to "发布任务", new_post_url %>
          </div>
          <div class="view-list-button">
            <%= link_to "任务列表", posts_url %>
          </div>
        </div>
      </div>
<% end %>


<div id="container">
  <div class="guider">
    <h2>How it works - 6 easy steps</h2>
    <div style="height:148px; ">
      <ul class="steps">
        <li class="step-model" style="width:40px;height: 10px;"> </li>
        <li class="step1 step-model"></li>
        <li class="arrow"></li>
        <li class="step2 step-model"></li>
        <li class="arrow"></li>
        <li class="step3 step-model"></li>
        <li class="arrow"></li>
        <li class="step4 step-model"></li>
        <li class="arrow"></li>
        <li class="step5 step-model"></li>
        <li class="arrow"></li>
        <li class="step6 step-model"></li>
      </ul>
    </div>
    <div class="step-item-detail">
      <div name ="step1" class="item left">注册登录后 用人单位和见习主管在大厅发布兼职任务</div>
      <div name ="step2" class="item left">自强帮注册用户 到任务列表竞拍兼职任务</div>
      <div name ="step3" class="item left">人数满后 企业确认支付 兼职金额到第三方 支付宝</div>
      <div name ="step4" class="item left">兼职工作拍得者为用人单位工作</div>
      <div name ="step5" class="item left">工作结束用人单位确认支付兼职费用</div>
      <div name ="step6" class="item left">双方互相评价，评选最佳兼职员工</div>
    </div>


  </div>

  <div class="latest-record">
    <div class="text"></div>
    <table class="mrw_list record" cellspacing="0" cellpadding="0" border="1">
      <tbody><tr style="" class="table-head">
          <th width="9%" align="left">任务赏金</th>
          <th width="34%" align="left">任务标题</th>
          <th width="9%">投标数量</th>
          <th width="11%">任务买家</th>
          <th width="16%">所需技能</th>
          <th width="9%">任务进度</th>
          <th width="12%">剩余时间</th>
        </tr>
        <!--神马网-->
        <!--神马网-->
        <!---->
        <% @posts.each do |post| %>
          <tr>
            <td><strong class="orange1">
                <%= "￥#{post.low_price}-#{post.high_price}" %>
              </strong></td>
            <td>
              <%= link_to post.title, post, :style=> "font-weight: normal;" %>
            </td>
            <td align="center">
              <%= post.comments.count %>
            </td>
            <td align="center">
              <%= link_to post.user.profile.name, worker_show_path(post.user.profile) %>
            </td>
            <td align="center">
              <%= join_skills(post) %>
            </td>
            <td align="center">
              <%= post.state %>
            </td>
            <td align="center"><u class="orange1">
                <%= how_long_over?(post) %>
              </u></td>
          </tr>
        <% end %>


      </tbody></table>
  </div>
</div>
<div class="ziqiangbang-space" style="width:1500px;height: 20px;"></div>

app/views/home/pay_sure.html.erb
<div>
  <%= @post.title %>
  <div>
    price: <%= @price %>
  </div>

  <div>
    <h2>准备支付给以下的工人</h2>
    <ul>
      <% @comments.each do |comment| %>
        <li>
          <span> <%= comment.user.profile.name %></span>
          <span> <%= comment.content %></span>
        </li>
      <% end %>
    </ul>
  </div>
  <%= link_to "确认付款", pay_post_path(@post) %>
</div>