config/routes.rb
Zilibang::Application.routes.draw do

  get "notices/index", :as => "accept_account"
  get "notices/error", :as => "refuse_account"
  get "notices/error_404", :as=> "error_404"
  get "notices/error_power", :as=> "error_power"
  get "home/index"

  root :to => "home#index"
  resource :user_session
  match "login" => "user_sessions#new", :as => :login
  match "register_check_instructions/:id" => "users#register_check_instructions", :as => :register_check_instructions
  match 'logout' => "user_sessions#destroy", :as => :logout
  get 'buyer_sure/:id' => "comments#buyer_sure", :as => :buyer_sure
  get 'buyer_cancel/:id' => "comments#buyer_cancel",  :as => :buyer_cancel
  get 'employer_sure/:id' => "comments#employer_sure", :as => :employer_sure
  get 'employer_cancel/:id' => "comments#employer_cancel",  :as => :employer_cancel
  get 'overpost/:id' => "posts#over", :as => :over_post
  get 'finish/:id' => "posts#finish", :as => :finish_post
  get 'pay_sure/:id' => "home#pay_sure", :as => :pay_sure_post
  get 'pay/:id' => "home#pay", :as => :pay_post
  post 'report_employer' => "comments#report_employer", :as => :report_employer
  post 'report_buyer' => "comments#report_buyer", :as => :report_buyer
  post 'verify' => "comments#verify_code", :as => :verify_code
  get 'mailer' => "home#mailer", :as => :mailer

  get 'forgot_password' => "users#forgot_password", :as => :forgot_password
  post 'forgot_password_sender' => "users#forgot_password_sender", :as => :forgot_password_sender
  get 'forgot_check_instructions/:id' => "users#forgot_check_instructions", :as => :forgot_check_instructions
  put 'update_user' => "users#update", :as => :update_user
  
  
  resources :users, :only => [:new, :create]
  resources :profiles, :only => [:show]
  get 'worker_show/:id' => "profiles#worker_show", :as => :worker_show
  get 'bussiness_show/:id' => "profiles#bussiness_show", :as => :bussiness_show
  resources :posts do
    post 'add_comment'
  end

  namespace :admin do
    get 'main/index'
    root :to => "main#index"
    resources :posts, :except => [:destroy]
    post 'posts/:id/pay' => "posts#pay", :as => :pay_post
    post 'posts/:id/destroy' => "posts#destroy", :as => :destroy_post
    resources :comments, :only => [:index, :edit, :update]
    post 'comments/:id/destroy' => "comments#destroy", :as => :destroy_comment
    resources :users do
      collection do
        get "change_password"
        put "update_password"
      end
    end
    post 'tags/:id/destroy' => "tags#destroy", :as => :destroy_tag
    resources :tags, :only => [:index, :new, :create]
    
  end

  namespace :center do
    root :to => "main#index"
    #resources :profiles, :only => [:show, :edit, :update]
    get 'profile' => 'profiles#show', :as => :profile
    get 'profile/edit' => 'profiles#edit', :as => :edit_profile
    put 'profile' => 'profiles#update', :as => :update_profile

    get 'change_password' => 'profiles#change_password', :as => :change_password
    put 'update_password' => 'profiles#password_update', :as => :update_change_password
    get 'messages' => 'messages#index', :as => :messages
    get 'message/show/:name' => 'messages#show',  :as => :show_message
    get 'messages/new' => 'messages#new', :as => :new_message
    post 'messages' => 'messages#create'
    post 'messages/:id/destroy' =>  'messages#destroy',  :as => :destroy_message
  end

end

app/models/post.rb
# coding: utf-8
class Post < ActiveRecord::Base
  self.per_page = 40
  belongs_to :user
  has_many :comments
  acts_as_taggable_on :skills
  attr_accessor :skill_listable
  apply_simple_captcha
  validates :title, :presence => true
  validates :description, :presence => true
  validates :longtime, :presence => true
  validates :tel,:low_price, :high_price, :presence => true
  validates_length_of :title, :minimum => 2
  validates_length_of :description, :minimum => 5
  validates_numericality_of :longtime, :only_integer => true,
                                       :greater_than_or_equal_to => 1,
                                       :less_than_or_equal_to => 100
  validates_format_of :tel, :with => /(13[0-9]|15[0|3|6|7|8|9]|18[8|9])\d{8}/,
                            :message => "请填写真实电话号码，方便任务双方联系"
  validates_numericality_of :low_price, :only_integer => true,
                                       :greater_than_or_equal_to => 10

  def skill_listable
    self.skill_list.map {|x| Tag.find_by_name(x)}
  end
end

app/controllers/admin/posts_controller.rb
# coding: utf-8
# To change this template, choose Tools | Templates
# and open the template in the editor.
class Admin::PostsController < Admin::BaseController
  #  load_and_authorize_resource
  main_nav_highlight :content
  sec_nav_highlight :posts
  def index
    @posts = Post.order("created_at DESC").paginate(:page => params[:page]||1, :per_page => 30)
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments
    @comment = @post.comments.new
    flash[:notice] = "xx"
  end
  
  def new
    @post = current_user.posts.new
  end
  
  def create
    @post = Post.new(params[:post])
    @post.save
    flash[:notice] = "create_successful"
    #respond_with(@user, :location => root_path())
    redirect_to admin_posts_path()
  end
  
  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    @post = Post.find(params[:id])
    @post.skill_list = []
    @post.save
    buffer = []
    params[:post]["skill_list"] = params[:post]["skill_ids"][1..-1]
    params[:post]["skill_list"].each do |tag|
      buffer << tag
    end
    params[:post].delete("skill_list")
    params[:post].delete("skill_ids")
    @post.skill_list = buffer
    @post.update_attributes(params[:post])

    flash[:notice] = "update_successful"
    redirect_to admin_posts_path()
  end
  
  # DELETE /news/1
  # DELETE /news/1.xml
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
  
    redirect_to admin_posts_path()
  end

  def pay
    @post = Post.find(params[:id])
    if current_user.role == 'admin'
      @post.paid = true
      @post.state = "雇主已经预付押金，等待中标者输入提现密码。"
      @post.save

      @verify_codes = []
      @post.comments.each do |comment|
        comment.code = verification
        comment.save
        @verify_codes << comment.user.profile.name.to_s+':'+comment.code.to_s
        current_user.delay.deliver_pay(comment.user,@post)
      end
      content = "<p>您发布的任务:#{@post.title} 已经付款，以下是各位工人的提款密码，请妥善保存，当确定工作完成后发放给工人，工人借此在自强帮网站上领取报酬</p>"
      @post.comments.each do |comment|
        if comment.code != nil
          content += "<p>#{comment.user.profile.name}:#{comment.code}</p>"
        end
      end
      current_user.delay.deliver_pay_code(@post.user,@post)
      flash[:notice] = "支付成功,请到您的用户中心查看您雇佣的工人的提现密码，并且我们已经把提现密码发送到您的邮箱中，请妥善保存！"
      redirect_to admin_posts_path()

    end
  end

end

app/controllers/posts_controller.rb
# coding: utf-8
class PostsController < ApplicationController
  load_and_authorize_resource
  def index
    @posts = Post.order("created_at DESC").paginate(:page => params[:page]||1, :per_page => 30)
  end

  def show
    @post = Post.find(params[:id])
    @have_comment = nil
    @comments = @post.comments
    @comment = @post.comments.new
    
    #flash[:notice] = "xx"
  end

  def create
    @post = Post.new(params[:post])
    @post.user = current_user
    
    buffers = []
    @post.skill_list.each do |skill|
      buffers << Tag.find(skill).name
    end

    @post.skill_list = buffers
    @post.state = "火热竞标中"
    if @post.valid?
      @post.save
      flash[:notice] = "创建成功"
      #respond_with(@user, :location => root_path())
      redirect_to posts_url
    else
      render :action => :new
    end
  end

  def edit
    @post = Post.find(params[:id])
    @flag = "edit"
  end

  def update
    @post = Post.find(params[:id])
    @post.skill_list = []
    @post.save
    buffer = []
    params[:post]["skill_list"] = params[:post]["skill_ids"][1..-1]
    params[:post]["skill_list"].each do |tag|
      buffer << tag
    end
    params[:post].delete("skill_list")
    params[:post].delete("skill_ids")
    @post.skill_list = buffer
    @post.update_attributes(params[:post])
    
    flash[:notice] = "update_successful"
    redirect_to posts_path()
  end

  # DELETE /news/1
  # DELETE /news/1.xml
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path()
  end

  def new
    redirect_to root_path if current_user == nil
    @post = current_user.posts.new
    @flag = "new"
  end

  def add_comment
    
    @comment = Comment.new(params[:comment])
    @comment.user = current_user
    @comment.post_id = params[:post_id]
    if @comment.valid_with_captcha?
      @comment.save
      flash[:notice] = "add comment success"
      current_user.delay.deliver_wait_employer_sure(@comment.post.user,@comment.post)
      redirect_to post_path(@comment.post_id)
    else
      flash[:notice] = "输入错误"
      redirect_to post_path(@comment.post_id)
    end
  end

  def over
    @post = Post.find(params[:id])
    if current_user == @post.user
      @post.over = true
      @post.state = "竞标结束，等待雇主付押金"
      @post.save
      @post.comments.each do |comment|
        if comment.buyer_sure == true and comment.employer_sure
          Message.create(:sender => User.find(1),:receiver => comment.user,:content =>"任务结束，竞标成功")
          current_user.delay.deliver_over_yes(comment.user,@post)
        else
          Message.create(:sender => User.find(1),:receiver => comment.user,:content =>"任务结束，竞标失败")
          current_user.delay.deliver_over_no(comment.user,@post)
        end
      end
#      current_user.delay.deliver_employer_over(@post.user,@post)
      redirect_to post_path(@post)
    end
  end

  def finish
    @post = Post.find(params[:id])
    if current_user == @post.user
      @post.state = "任务结束，请互相评分来提高信用等级"
      @post.finish = true
      @post.save
      @post.comments.each do |comment|
        if comment.buyer_sure == true and comment.employer_sure
          Message.create(:sender => User.find(1),:receiver => comment.user,:content =>"工作完成")
#          current_user.delay.deliver_finish(comment.user,@post)
        end
      end
    end
    flash[:notice] = "bussiness success"
    redirect_to post_path(@post)
  end


end

app/helpers/posts_helper.rb
# coding: utf-8
module PostsHelper
  def comfortable?(level)
    result = case
    when level == 2
      "好评"
    when level == 1
      "中评"
    when level == -1
      "差评"
    end
  end
end

app/views/posts/_entries.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>


  <div>
    <h2>任务列表</h2>
    <ul class="record-list-nav">
	<li><%= link_to "返回首页", root_path(), :class => "left" %></li>
	<li><%= link_to "发布任务", new_post_path(), :class => "left" %></li>
</ul>
    <div class="flickr_pagination">

    <%=h will_paginate @posts %>
    </div>
    <table class="mrw_list record" cellspacing="0" cellpadding="0" border="1">
      <tbody><tr style="" class="table-head">
          <th width="9%" align="left">任务赏金</th>
          <th width="34%" align="left">任务标题</th>
          <th width="9%">投标数量</th>
          <th width="11%">任务买家</th>
          <th width="16%">所需技能</th>
          <th width="9%">任务进度</th>
          <th width="12%">剩余时间</th>
        </tr>
        <!--神马网-->
        <!--神马网-->
        <!---->
        <% @posts.each do |post| %>
          <tr>
            <td><strong class="orange1">
                <%= "￥#{post.low_price}-#{post.high_price}" %>
              </strong></td>
            <td>
              <%= link_to post.title, post, :style=> "font-weight: normal;" %>
            </td>
            <td align="center">
              <%= post.comments.count %>
            </td>
            <td align="center">
              <%= link_to post.user.profile.name, post.user.profile %>
            </td>
            <td align="center">
              <%= join_skills(post) %>
            </td>
            <td align="center">
              <%= post.state %>
            </td>
            <td align="center"><u class="orange1">
                <%= how_long_over?(post) %>
              </u></td>
          </tr>
        <% end %>


      </tbody></table>
        <div class="flickr_pagination">

    <%=h will_paginate @posts %>
    </div>
  </div>

app/views/posts/_form.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>
<%= form.inputs do %>
  <%= form.input :title, :input_html => { :class => "text-input medium-input" }, :label=> "任务标题" %>
  <%= form.input :description, :input_html => { :class => "text-input medium-input" }, :label => "任务描述" %>
  <%= form.input :longtime, :input_html => { :class => "text-input medium-input" }, :label => "任务有效天数" %>
  <%= form.input :tel, :input_html => { :class => "text-input medium-input" }, :label=>"任务联系电话" %>
  <%= form.input :low_price, :input_html => { :class => "text-input medium-input" }, :label => "可接受的最低价" %>
  <%= form.input :high_price, :input_html => { :class => "text-input medium-input" }, :label => "可接受的最高价" %>
  <% if @flag == "new" %>
    <%= form.input :skill_list, :as => :check_boxes, :collection => Tag.all, :value_method => :name, :label => "任务所需的技能", :label_html => { :class => "skills" }, :value_method => Proc.new { |a| a.id } %>
  <% elsif @flag == "edit" %>
    <%= form.input :skills, :as => :check_boxes, :collection => Tag.all, :value_method => :name, :label => "任务所需的技能", :label_html => { :class => "skills" }, :value_method => Proc.new { |a| a.id } %>
  <% end %>
<%#= form.input :captcha, :as => :simple_captcha, :label => "验证码" %>
<% end %>

<%= form.buttons do %>
  <%= form.commit_button :button_html => { :class => "button" } %>
<% end %>

app/views/posts/edit.html.erb
<h3>任务管理</h3>

<ul class="shortcut-buttons-set">
	<li><%= link_to "返回控制面板", root_path(), :class => "shortcut-button home" %></li>
	<li><%= link_to "返回分类列表", root_path(), :class => "shortcut-button episode" %></li>
</ul>

<div class="clear"></div>

<div class="content-box">
	<div class="content-box-header">
		<h3>修改任务</h3>
	</div>

	<div class="content-box-content">
		<%= semantic_form_for(@post, :url => post_path(@post), :html => { :multipart => true }) do |f| %>
			<%= render :partial => 'form', :object => f %>
		<% end %>
	</div>
</div>

app/views/posts/index.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>





<div class="c"></div>

<div style="margin-top: 15px;">
	<div class="record-list-left left">
          <%= image_tag "ad1.png"  %>
	</div>

	<div class="record-list-right left">
                
          <%= image_tag "ad3.gif" %>
		<% if @posts.blank? %>
			<p>暂无任务,您可以<%= link_to "添加任务", new_post_path() %>！</p>
		<% else %>
			<%= render "entries" %>
                        
		<% end %>
                        <%= image_tag "ad2.jpg" %>
	</div>
</div>

app/views/posts/new.html.erb
<h3>发布新任务</h3>

<ul class="shortcut-buttons-set">
	<li><%= link_to "返回首页", root_path(), :class => "shortcut-button home" %></li>
	<li><%= link_to "返回任务大厅", posts_path(), :class => "shortcut-button user" %></li>
</ul>

<div class="clear"></div>

<div class="content-box">
	<div class="content-box-header">
		<h3>添加任务</h3>
	</div>

	<div class="content-box-content">
		<%= semantic_form_for(@post, :url => posts_path(), :validate => true, :html => { :multipart => true }) do |form| %>
			<%= render :partial => 'form', :object => form %>
		<% end %>
	</div>
</div>

app/views/posts/show.html.erb
<% if @post.over == true %>
<div style ="border:2px solid #666; width:300px; margin: 4px">
  <h3><div style="color: red">您错过了投标的时间,该任务已经结束了！</div></h3>

</div>
<% end %>
<div id="internalContent">
  <img src="/images/internal_content_top.gif" alt="" width="902" height="12"></img>
  <div id="projectDetailsOverview">
    <div class="column1">
      <p><strong>任务标题: </strong><span class="project_status_A" align="left">
          <%= @post.title %>
        </span>
      </p>
      <img src="//cdn5.freelancer.com/img/spacer.gif" alt="" width="20" height="8" class="homeHeaderSizer"></img>
      <p>
        <strong>离结束还有</strong>
        <%= how_long_over?(@post) %>
      </p>
      <img src="//cdn5.freelancer.com/img/spacer.gif" alt="" width="20" height="8" class="homeHeaderSizer"></img>
      <p><strong>可接受报价: </strong><%= "￥:#{@post.low_price} - #{@post.high_price}" %></p>
      <img src="//cdn5.freelancer.com/img/spacer.gif" alt="" width="20" height="8" class="homeHeaderSizer"></img>
      <p><strong>创建时间 </strong><%=  @post.created_at %></p>
    </div>
    <div class="column2">
      <p><strong>竞标人数: </strong>  <span class="bidCount"><%= @post.comments.count %></span></p>
      <img src="//cdn5.freelancer.com/img/spacer.gif" alt="" width="20" height="9" class="homeHeaderSizer"/>

      <p><strong>任务天数: </strong><br/>  <%= @post.longtime %> </p>
      <p><strong>联系电话: </strong><br/> <%= @post.tel %>  </p>
    </div>
    <div class="column3">
      <p><strong>创建者:</strong>
        <%= link_to @post.user.profile.name, bussiness_show_path(@post.user.profile) %>
        <img src="/images/offline_man.png" width="18" height="22" title="Offline"/>




        <br/>


        <img src="//cdn5.freelancer.com/img/spacer.gif" alt="" width="355" height="8" class="homeHeaderSizer"/>

      </p>
    </div>
    <% if @post.over == false %>
    <div class="column4">

      <a href="#addcomment" rel="nofollow"><img alt="Bid On This Project" src="/images/btn_bid_on_project.gif" width="167" height="36" border="0"/></a>

    </div>
    <% end %>
    <p><strong>任务状态: </strong><br/>  <%= @post.state %> </p>

  </div>
  <div class="c">&nbsp;</div>

  <div id="projectDetails">
    <img src="//cdn3.freelancer.com/img/internal/project/project_content_top.gif" alt="" width="866" height="10"/>
    <div id="projectDetailsContent" style="width:826px; word-wrap:break-word;">
      <h3>任务描述</h3>
      <br/>
      <table style="width: 826px; border-width: 0px; border-style: none; border-spacing: 0px;">
        <tbody><tr><td style="width:100%;">
              <%= @post.description %>
            </td>
            <td style="padding-left:5px;">
              <a href="http://ox-d.freelancer.com/w/1.0/rc?ts=0c2lkPTUwMTB8YXVpZD0zMTc5MnxhaWQ9NjE5MDF8cHViPTc0NDh8bGlkPTQzMjk5fHQ9MXxyaWQ9MWVmYmI0NTQtNTRkNy00NGEwLTgwZGQtMjI1NDJlOWRjMTlmfG9pZD0xNTM5MHxibT1CVVlJTkcuSE9VU0V8cGM9QVVEfGFjPUFVRHxwbT1QUklDSU5HLkNQTXxydD0xMzEzODIzMzQzfGFkdj03NjQ3" target="_blank">
                <img src="http://ox-i.freelancer.com/fde/fdebec09-eb04-41c1-8838-6e8db98157ce/b56/b5663273994fcc2c7a0cf182b9242683.gif" height="250" width="300" border="0" alt=""/>
              </a>

            </td>
          </tr>
          <tr>
            <td>
              <div>
                <% if @post.user == current_user %>
                  <% if @post.over == true %>
                    已经被您结束了哦
                    <% if @post.paid == false %>
                      <%= link_to "付押金[?]", pay_sure_post_path(@post) %>
                    <% else %>
                      已经付款了
                      <% if @post.finish == false %>
                        <%= link_to "工人已经为我完成了工作！", finish_post_path(@post) %>
                      <% else %>
                        这个任务已经结束了

                      <% end %>
                    <% end %>
                  <% else %>
                    <%= link_to "结束任务", over_post_path(@post) %>
                  <% end %>

                <% end %>
              </div>
            </td>
          </tr>
        </tbody></table>




      <div align="right">
        <a href="#" onclick="return reportProject();" style="color:#cc0000;"><font color="#cc0000">Report Violation</font></a>
      </div>


      <br/>
      <div class="horizontalLine"><img src="/images/dadada.gif" alt=" " width="834" height="1" /></div>

      <div id="projectTechnicalSummary">
        <div class="column1">

          <img src="/images/spacer.gif" alt="" width="1" height="7" class="homeHeaderSizer"/>

          <div style="padding:5px 0px 5px 0px" class="tags"><b>需要技能:</b>
            <% @post.skills.each do |skill|%>
              <a class ="post-tag"><%=  skill %></a>
            <% end %>
          </div>


        </div>
      </div>

    </div>

    <img src="//cdn5.freelancer.com/img/internal/project/project_content_bottom.gif" alt="" width="866" height="10" />
  </div>

  <div style="margin-top: 10px; position: relative; ">
    <div id="bidders-section">
      <h2>所有投标</h2>

    </div>
    <div class="bidHead">
      <span class="th0">

        <span class="bidders-section-heading">竞标者</span>

      </span>
      <span class="th2">

        <span class="bidders-section-heading">报价</span>

      </span>
      <span class="th3">
        <span class="bidders-section-heading">竞标时间</span>

      </span>
      <span class="th4">

        <span class="bidders-section-heading">功能区</span>
      </span>
      <span style="clear:both;"></span>
    </div>
    <div class="bidders-container nonwinbids">
      <% @comments.each do |comment| %>
        <div class="serviceProviderDetails">
          <div class="brwrap">
            <div class="brsec top1">
              <%= image_tag comment.user.profile.avatar(:thumb) %>
              <div><%= link_to comment.user.profile.name, worker_show_path(comment.user.profile) %></div>
            </div>
            <div class="brsec top3">
              <%= comment.price %>
            </div>

            <div class="brsec top4">
              <%= comment.created_at %>
            </div>

            <div class="brsec top5">
              <div>
                <% if @post.paid == true and comment.buyer_sure == true and comment.employer_sure == true and @user == @post.user%>
                  <p>电话 <%= comment.user.profile.tel %> </p>
                <% end %>
              </div>
              <div>
                <% if comment.user == current_user or @post.user == current_user%>
                  <% @have_comment = true %>
                  <p>
                    <% if comment.buyer_sure == true %>
                      企业已确认
                    <% else %>
                      企业考虑中
                    <% end %>
                    |
                    <% if comment.buyer_sure == true %>
                      <% if comment.employer_sure == true %>
                        受雇佣者已确认
                      <% else %>
                        还没上线确认信息哦～
                      <% end %>
                    <% else %>
                      等待中标
                    <% end %>
                  </p>
                <% end %>
              </div>
              <div>
                <% if @post.over == false %>

                  <% if @post.user == current_user %>
                    <% if comment.buyer_sure != true %>
                      <%= link_to "企业确认", buyer_sure_path(comment) %>
                    <% else %>
                      <%= link_to "取消确认", buyer_cancel_path(comment) %>
                    <% end %>
                  <% end %>

                  <% if comment.user == current_user and comment.buyer_sure == true%>

                    <% if comment.employer_sure != true %>
                      <%= link_to "受雇者确认", employer_sure_path(comment) %>
                    <% else %>
                      <%= link_to "取消确认", employer_cancel_path(comment)  %>
                    <% end %>
                  <% end %>

                <% else %>
                  <% if comment.buyer_sure == true and comment.employer_sure == true %>
                    竞标成功！
                  <% else %>
                    竞标失败！
                  <% end %>
                <% end %>
              </div>

              <div>
                <% if comment.verified == false %>
                请在下面输入提现密码
                <% else %>
                提现密码验证成功
                <% end %>
              </div>



          </div>

        </div>
        <div class="c"></div>
        <div class="msg">
          <%= comment.content %>
        </div>
            <% if @post.paid == true and comment.user == current_user%>
      <% if comment.verified == false %>

        <%= semantic_form_for "", :url=> verify_code_url do |form| %>
          <%= form.input :code, :label => "提现密码" %>
          <%= form.input :id, :as => :hidden, :value => comment.id %>
          <%= form.buttons do %>
            <%= form.commit_button :button_html => { :value => "提交"} %>
          <% end %>
        <% end %>
      <%  else %>
        <h1>提现密码验证成功</h1>

      <% end %>
    <% end %>

                      <div>
                <% if @post.user == current_user and @post.finish == true %>
                  <div>
                    <% if comment.buyer_level == 0 %>
                      请您来评价评价工人

                      <%= semantic_form_for "", :url=> report_buyer_url do |form| %>
                        <%= form.input :content %>
                        <%= form.input :level,   :as => :radio,       :collection => ["好评", "中评", "差评"] %>
                        <%= form.input :id, :as => :hidden, :value => comment.id %>
                        <%= form.buttons do %>
                          <%= form.commit_button :button_html => { :value => "评价"} %>
                        <% end %>
                      <% end %>
                    <% end %>
                  </div>
                <% end %>
                <!-- 工人评价企业的地方-->
                <% if comment.user == current_user and @post.finish == true%>
                  <div>
                    <% if comment.employer_level == 0 %>
                      请您来评价企业
                      <%= semantic_form_for "", :url=> report_employer_url do |form| %>
                        <%= form.input :content, :label => "评价内容" %>
                        <%= form.input :level,   :as => :radio,       :collection => ["好评", "中评", "差评"], :label => "评价等级" %>
                        <%= form.input :id, :as => :hidden, :value => comment.id %>
                        <%= form.buttons do %>
                          <%= form.commit_button :button_html => { :value => "评价"} %>
                        <% end %>
                      <% end %>
                    <% end %>
                  </div>
                <% end %>

                <div>
                  <% if comment.buyer_level != 0  %>
                    企业对工人的评价:
                    <%= "#{comment.buyer_content}-" %>
                    <%=comfortable?(comment.buyer_level)  %><br />
                  <% end %>

                  <% if comment.employer_level != 0 %>
                    工人对企业的评价:
                    <%= "#{comment.employer_content}" %>
                    <%=comfortable?(comment.employer_level)  %>
                  <% end %>
                </div>

            </div>
      </div>

    <% end %>
    </div>


    <img src="//cdn6.freelancer.com/img/internal/internal_content_bottom.gif" alt="" width="902" height="12"/>
  </div>



</div>
<!-- xx  -->





<% if @post.user != current_user and @have_comment != true%>
<% if @post.over == false %>
  <h3 id="addcomment">竞标区</h3>


  <%= form_for @comment, :url => post_add_comment_path(@post), :method => :post, :html => { :id => "commentform" }, :validate => true do |f| %>

    <p>
      金额(至少10元)：
    </p>
    <p>
      <%= f.text_field :price, :validate => true  %>
    </p>
    <p>
      内容：
    </p>
    <p>
      <%= f.text_area :content, :cols => 60, :rows => 10, :tabindex => 4 %>
    </p>
    <p>
      <%= f.simple_captcha :label => "验证码" %>
    </p>

    <p>
      <input name="submit" type="submit" id="submit" tabindex="5" value="确定投标" />
      <input type="hidden" name="comment_post_ID" value="92" />
    </p>

  <% end %>
<% else %>
  
<% end %>
<% end %>

<%= link_to "返回", posts_path() %>