config/routes.rb
Zilibang::Application.routes.draw do

  get "notices/index", :as => "accept_account"
  get "notices/error", :as => "refuse_account"
  get "notices/error_404", :as=> "error_404"
  get "notices/error_power", :as=> "error_power"
  get "home/index"

  root :to => "home#index"
  resource :user_session
  match "login" => "user_sessions#new", :as => :login
  match "register_check_instructions/:id" => "users#register_check_instructions", :as => :register_check_instructions
  match 'logout' => "user_sessions#destroy", :as => :logout
  get 'buyer_sure/:id' => "comments#buyer_sure", :as => :buyer_sure
  get 'buyer_cancel/:id' => "comments#buyer_cancel",  :as => :buyer_cancel
  get 'employer_sure/:id' => "comments#employer_sure", :as => :employer_sure
  get 'employer_cancel/:id' => "comments#employer_cancel",  :as => :employer_cancel
  get 'overpost/:id' => "posts#over", :as => :over_post
  get 'finish/:id' => "posts#finish", :as => :finish_post
  get 'pay_sure/:id' => "home#pay_sure", :as => :pay_sure_post
  get 'pay/:id' => "home#pay", :as => :pay_post
  post 'report_employer' => "comments#report_employer", :as => :report_employer
  post 'report_buyer' => "comments#report_buyer", :as => :report_buyer
  post 'verify' => "comments#verify_code", :as => :verify_code
  get 'mailer' => "home#mailer", :as => :mailer

  get 'forgot_password' => "users#forgot_password", :as => :forgot_password
  post 'forgot_password_sender' => "users#forgot_password_sender", :as => :forgot_password_sender
  get 'forgot_check_instructions/:id' => "users#forgot_check_instructions", :as => :forgot_check_instructions
  put 'update_user' => "users#update", :as => :update_user
  
  
  resources :users, :only => [:new, :create]
  resources :profiles, :only => [:show]
  get 'worker_show/:id' => "profiles#worker_show", :as => :worker_show
  get 'bussiness_show/:id' => "profiles#bussiness_show", :as => :bussiness_show
  resources :posts do
    post 'add_comment'
  end

  namespace :admin do
    get 'main/index'
    root :to => "main#index"
    resources :posts, :except => [:destroy]
    post 'posts/:id/pay' => "posts#pay", :as => :pay_post
    post 'posts/:id/destroy' => "posts#destroy", :as => :destroy_post
    resources :comments, :only => [:index, :edit, :update]
    post 'comments/:id/destroy' => "comments#destroy", :as => :destroy_comment
    resources :users do
      collection do
        get "change_password"
        put "update_password"
      end
    end
    post 'tags/:id/destroy' => "tags#destroy", :as => :destroy_tag
    resources :tags, :only => [:index, :new, :create]
    
  end

  namespace :center do
    root :to => "main#index"
    #resources :profiles, :only => [:show, :edit, :update]
    get 'profile' => 'profiles#show', :as => :profile
    get 'profile/edit' => 'profiles#edit', :as => :edit_profile
    put 'profile' => 'profiles#update', :as => :update_profile

    get 'change_password' => 'profiles#change_password', :as => :change_password
    put 'update_password' => 'profiles#password_update', :as => :update_change_password
    get 'messages' => 'messages#index', :as => :messages
    get 'message/show/:name' => 'messages#show',  :as => :show_message
    get 'messages/new' => 'messages#new', :as => :new_message
    post 'messages' => 'messages#create'
    post 'messages/:id/destroy' =>  'messages#destroy',  :as => :destroy_message
  end

end

app/models/user.rb
# coding: utf-8
class User < ActiveRecord::Base
  ROLES = %w[admin user guest]
  validates_acceptance_of :terms_of_service
#  apply_simple_captcha
#  validates :email, :presence => true
#  validates :password, :presence => true
  acts_as_authentic do |c|
    c.login_field = :email
  end
  acts_as_taggable_on :skills
  attr_accessor :old_password
  attr_protected :superadmin
  #attr_accessible :profile
  validate :validate_old_password, :if => :required_old_password?

  has_one :profile, :dependent => :destroy
  accepts_nested_attributes_for :profile,
    :allow_destroy => true

  has_many :posts
  has_many :comments
  has_many :sendments, :class_name => "Message", :foreign_key => "sender_id"
  has_many :receivements, :class_name => "Message", :foreign_key => "receiver_id"
  def validate_old_password
    errors.add(:old_password) unless valid_password?(self.old_password)
  end

  def required_old_password!
    @old_password_required = true
    @password_changed = true
  end

  def required_old_password?
    @old_password_required
  end

  def deliver_register_instructions!
    reset_perishable_token!
    UserMailer.welcome_email(self).deliver
  end

  def deliver_forgot_instructions!
    reset_perishable_token!
    UserMailer.forgot_email(self).deliver
  end

  def deliver_pay(user,post)
    UserMailer.pay(user,post).deliver
  end
  def deliver_pay_code(user,post)
    UserMailer.pay_code(user,post).deliver
  end
  def deliver_finish(user,post)
    UserMailer.finish(user,post).deliver
  end
  def deliver_over_no(user,post)
    UserMailer.over_no(user,post).deliver
  end
  def deliver_over_yes(user,post)
    UserMailer.over_yes(user,post).deliver
  end
  def deliver_wait_buyer_sure(user,post)
    UserMailer.wait_buyer_sure(user,post).deliver
  end
  def deliver_wait_employer_sure(user,post)
    UserMailer.wait_employer_sure(user,post).deliver
  end
  def deliver_buyer_sure(user,post)
    UserMailer.buyer_sure(user,post).deliver
  end
  def deliver_buyer_cancel(user,post)
    UserMailer.buyer_cancel(user,post).deliver
  end
  def deliver_employer_sure(user,post)
    UserMailer.employer_sure(user,post).deliver
  end
  def deliver_employer_cancel(user,post)
    UserMailer.employer_cancel(user,post).deliver
  end
  def deliver_employer_over(user,post)
    UserMailer.employer_over(user,post).deliver
  end
  def deliver_verify_code(user,post)
    UserMailer.verify_code(user,post).deliver
  end
  def deliver_report_buyer(user,post)
    UserMailer.report_buyer(user,post).deliver
  end
  def deliver_report_employer(user,post)
    UserMailer.report_employer(user,post).deliver
  end
  def role?(base_role)
    ROLES.index(base_role.to_s) <= ROLES.index(role)
  end

  def system_messages
    self.receivements.select {|message| message.sender.id == 1}
  end

  def add_score!(level, tag)
    tag_id = Tag.find_by_name(tag).id

    if have_not?(tag)
      self.skill_list << tag
      self.save
    end
    tagging = Tagging.where("taggable_id = #{self.id} AND tag_id = #{tag_id} AND taggable_type = \"User\"").first
    tagging.score += level.to_i*10
    tagging.save
  end

  def have_not?(tag)
    return false if self.skill_list.include?(tag)
    true
  end
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  main_nav_highlight :system
  sec_nav_highlight :users
  before_filter :find_user, :except => [ :index, :new, :create, :change_password, :update_password ]

  def index
#    @scope = User.where(:superadmin => false)
#    @users = @scope.paginate(:page => params[:page])
     @users = User.paginate(:page => params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    @user.save
    flash[:notice] = t(:create_successful)
    respond_with(@user, :location => admin_users_path())
  end

  def edit
  end

  def update
    @user.update_attributes(params[:user])
    flash[:notice] = "update_successful"
    respond_with(@user, :location => admin_users_path())
  end

  def change_password
  end

  def update_password
    current_user.required_old_password!

    if current_user.update_attributes(params[:user])
      redirect_to admin_root_path(), :notice => t(:password_update_successfully)
    else
      render :change_password
    end
  end

  def destroy
    @user.destroy
    flash[:notice] = t(:operate_successful)
    respond_with(@user, :location => admin_users_path())
  end

  def find_user
    @user = User.find(params[:id])
  end


end

app/controllers/users_controller.rb
# coding: utf-8
class UsersController < ApplicationController
  #layout :nil
  def new
    @user = User.new
    @user.build_profile
  end

  def create
    @user = User.new(params[:user])
    @user.role = "guest"
    if @user.valid?
      @user.save
      @user.reset_perishable_token!
      @user.delay.deliver_register_instructions!
      flash[:notice] = "创建成功，请查收您邮箱中自强帮发来的邮件"
      redirect_to root_path()
    else
      render :action => :new
    end
    
    #respond_with(@user, :location => root_path())
    
  end

  def update
    @user = User.find_by_persistence_token(params[:user][:persistence_token])
    params[:user][:role] = "user"
    @user.update_attributes(params[:user])
    flash[:notice] = "修改密码成功"
    redirect_to root_url
  end

  def register_check_instructions
    @user = User.find_using_perishable_token(params[:id])
    
    if @user != nil
      @user.role = "user"
      @user.save
      #flash[:notice] = "accept your account"
      redirect_to accept_account_url
    else
      redirect_to refuse_account_url
    end
  end

  def forgot_password
    @user = User.new
  end

  def forgot_password_sender
    email = params[:user][:email]
    @user = User.find_by_email(email)
    @user.delay.deliver_forgot_instructions!
    flash[:notice] = "发送成功"
    redirect_to root_url

  end

  def forgot_check_instructions
    @user = User.find_using_perishable_token(params[:id])
    if @user == nil
      flash[:notice] = "please show your real token for us"
      redirect_to root_url
    end
  end
end

app/views/admin/users/_entries.html.erb
<table>
	<thead>
		<tr>
			<th> id </th>
			<th> 登录邮箱</th>
                        <th> 权限 </th>
			<th> 上次活动 </th>
			<th> 登录次数 </th>
			<th> 注册时间 </th>
			<th> 功能 </th>
		</tr>
	</thead>

	<tbody>
		<% @users.each do |user| %>
		<tr>

			<td><%= user.id %></td>
			<td><%= user.email %></td>
                        <td><%= user.role %></td>
			<td><%= user.last_request_at %></td>
			<td><%= user.login_count %></td>
			<td><%= user.created_at %></td>
			<td>
				<%= link_to "edit", edit_admin_user_path(user), :title => :edit, :class => "edit" %>&nbsp;
				<%= link_to "delete", admin_user_path(user), :method => :delete, :confirm => :delete_confirm, :title => :delete, :class => "delete" %>
			</td>
		</tr>
		<% end %>
	</tbody>

	<tfoot>
		<tr>
			<td colspan="4">
				<%= render :partial => "admin/shared/pagination", :locals => { :pagination => @users } %>
				<div class="clear"></div>
			</td>
		</tr>
	</tfoot>
</table>

app/views/admin/users/_form.html.erb
<%= form.inputs do %>
	<%= form.input :email, :input_html => { :class => "text-input medium-input" } %>
	<%= form.input :password, :input_html => { :class => "text-input medium-input" } %>
	<%= form.input :password_confirmation, :input_html => { :class => "text-input medium-input" } %>
        <%= form.collection_select :role, User::ROLES, :to_s, :humanize %>
<% end %>

<%= form.buttons do %>
	<%= form.commit_button :button_html => { :class => "button" } %>
<% end %>

app/views/admin/users/change_password.html.erb
<h3>用户密码修改</h3>

<ul class="shortcut-buttons-set">
	<li><%= link_to "返回控制面板", admin_root_path(), :class => "shortcut-button home" %></li>
</ul>

<div class="clear"></div>

<div class="content-box">
	<div class="content-box-header">
		<h3>修改 <%= current_user.login %>的密码</h3>
	</div>

	<div class="content-box-content">
		<%= semantic_form_for(current_user, :url => update_password_admin_users_path(), :method => :put) do |form| %>
			<%= form.inputs do %>
				<%= form.input :old_password, :input_html => { :class => "text-input medium-input" } %>
				<%= form.input :password, :input_html => { :class => "text-input medium-input" } %>
				<%= form.input :password_confirmation, :input_html => { :class => "text-input medium-input" } %>
			<% end %>

			<%= form.buttons do %>
				<%= form.commit_button true, :button_html => { :class => "button" } %>
			<% end %>
		<% end %>
	</div>
</div>

app/views/admin/users/edit.html.erb
<h3>用户管理模块</h3>

<ul class="shortcut-buttons-set">
	<li><%= link_to "返回控制面板", admin_root_path(), :class => "shortcut-button home" %></li>
	<li><%= link_to "返回用户管理列表", admin_users_path(), :class => "shortcut-button user" %></li>
</ul>

<div class="clear"></div>

<div class="content-box">
	<div class="content-box-header">
		<h3>修改用户</h3>
	</div>

	<div class="content-box-content">
		<%= semantic_form_for(@user, :url => admin_user_path(@user)) do |f| %>
			<%= render :partial => 'form', :object => f %>
		<% end %>
	</div>
</div>

app/views/admin/users/index.html.erb
<h2>用户管理模块</h2>

<ul class="shortcut-buttons-set">
	<li><%= link_to "返回控制面板", admin_root_path(), :class => "shortcut-button home" %></li>
	<li><%= link_to "添加用户", new_admin_user_path(), :class => "shortcut-button user" %></li>
</ul>

<div class="clear"></div>

<div class="content-box">
	<div class="content-box-header">
		<h3>用户列表</h3>
	</div>

	<div class="content-box-content">    
		<% if @users.blank? %>
			<p>暂无普通用户记录,您可以<%= link_to "添加用户", new_admin_user_path() %>！</p>
		<% else %>
                        <%= @users.count %>
			<%= render "entries" %>
		<% end %>
	</div>
</div>

app/views/admin/users/new.html.erb
<h3>用户管理模块</h3>

<ul class="shortcut-buttons-set">
	<li><%= link_to "返回控制面板", admin_root_path(), :class => "shortcut-button home" %></li>
	<li><%= link_to "返回用户管理列表", admin_users_path(), :class => "shortcut-button user" %></li>
</ul>

<div class="clear"></div>

<div class="content-box">
	<div class="content-box-header">
		<h3>添加用户</h3>
	</div>

	<div class="content-box-content">
		<%= semantic_form_for(@user, :url => admin_users_path(), :html => { :multipart => true }) do |f| %>
			<%= render :partial => 'form', :object => f %>
		<% end %>
	</div>
</div>